connections:
- destination: &id001
    configuration:
      database: email_analytics
      host: '{{ var.value.postgres_host }}'
      password: '{{ var.value.postgres_password }}'
      port: 5432
      schema: raw_emails
      username: '{{ var.value.postgres_user }}'
    connector_type: destination-postgres
    name: PostgreSQL
  name: webhook_email_connection
  schedule:
    cron_expression: 0 */1 * * *
    schedule_type: cron
  source: &id002
    configuration:
      batch_size: 100
      credentials:
        auth_type: oauth2
        client_id: '{{ var.value.gmail_client_id }}'
        client_secret: '{{ var.value.gmail_client_secret }}'
        refresh_token: '{{ var.value.gmail_refresh_token }}'
      query: is:unread
      start_date: '2024-01-01T00:00:00Z'
    connector_type: source-gmail
    name: Gmail
  sync_mode: incremental
- destination: *id001
  name: streaming_source_connection
  schedule:
    cron_expression: 0 */1 * * *
    schedule_type: cron
  source: *id002
  sync_mode: incremental
project_name: email_analytics_realtime_email_analysis
version: 0.50.0
